apiVersion: v1
kind: Secret
metadata:
  name: expiration-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  CLIENT_URL: 'http://localhost:3000'
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-srv:5672"
  REDIS_URL: "redis://redis-srv:6379"
  SERVICE_NAME: 'Expiration Service'