apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  DB_HOST: 'order-postgres-srv'
  DB_PORT: '5432'
  DB_NAME: 'order'
  DB_USER: 'postgres'
  DB_PASS: '123456'
  JWT_PRIVATE_KEY: ']k?+MjU5omLRg@GujHxw}ZH4#n#YF*+i}wQcd}#z.EqdwuF~^^z'
  JWT_EXPIRES: '36000000'
  BCRYPT_SALT: '10'
  CLIENT_URL: 'http://localhost:3000'
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-srv:5672"
  SERVICE_NAME: 'Order Service'