apiVersion: v1
kind: Secret
metadata:
  name: ticket-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  DB_HOST: 'ticket-postgres-srv'
  DB_PORT: '5432'
  DB_NAME: 'ticket'
  DB_USER: 'postgres'
  DB_PASS: '123456'
  JWT_PRIVATE_KEY: ']k?+MjU5omLRg@GujHxw}ZH4#n#YF*+i}wQcd}#z.EqdwuF~^^z'
  JWT_EXPIRES: '36000000'
  BCRYPT_SALT: '10'
  CLIENT_URL: 'http://localhost:3000'
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-srv:5672"
  SERVICE_NAME: 'Ticket Service'

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  DB_HOST: 'auth-postgres-srv'
  DB_PORT: '5432'
  DB_NAME: 'auth'
  DB_USER: 'postgres'
  DB_PASS: '123456'
  JWT_PRIVATE_KEY: ']k?+MjU5omLRg@GujHxw}ZH4#n#YF*+i}wQcd}#z.EqdwuF~^^z'
  JWT_EXPIRES: '36000000'
  BCRYPT_SALT: '10'
  CLIENT_URL: 'http://localhost:3000'
  SERVICE_NAME: 'Authentication Service'

---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  DB_HOST: 'order-postgres-srv'
  DB_PORT: '5432'
  DB_NAME: 'order'
  DB_USER: 'postgres'
  DB_PASS: '123456'
  JWT_PRIVATE_KEY: ']k?+MjU5omLRg@GujHxw}ZH4#n#YF*+i}wQcd}#z.EqdwuF~^^z'
  JWT_EXPIRES: '36000000'
  BCRYPT_SALT: '10'
  CLIENT_URL: 'http://localhost:3000'
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-srv:5672"
  SERVICE_NAME: 'Order Service'

---

apiVersion: v1
kind: Secret
metadata:
  name: expiration-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  CLIENT_URL: 'http://localhost:3000'
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-srv:5672"
  REDIS_URL: "redis://redis-srv:6379"
  SERVICE_NAME: 'Expiration Service'

---


apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
stringData:
  PORT: '3000'
  NODE_ENV: 'development'
  DB_HOST: 'payment-postgres-srv'
  DB_PORT: '5432'
  DB_NAME: 'payment'
  DB_USER: 'postgres'
  DB_PASS: '123456'
  JWT_PRIVATE_KEY: ']k?+MjU5omLRg@GujHxw}ZH4#n#YF*+i}wQcd}#z.EqdwuF~^^z'
  JWT_EXPIRES: '36000000'
  BCRYPT_SALT: '10'
  CLIENT_URL: 'http://localhost:3000'
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-srv:5672"
  SERVICE_NAME: 'Payment Service'